### ISSUE TITLE
单端口多用户配置 Tcpreplay.py  第1056、1058、899行报故

### ISSUE THREAD

**Issue by hawkhu** [esdeathlove/shadowsocks#28]
按照v3魔改项目里的wiki配置了单端口多用户，在连接时客户端提示：

> connection closed by  peer

无法连接，用tail.sh查看log，发现有如下输出：

> 2016-12-21 23:51:17 WARNING  tcprelay.py:483 TCP data redir zhaoj.in:80 03087a68616f6a2e696e0050
> 2016-12-21 23:51:17 ERROR    tcprelay.py:1056 [Errno 104] Connection reset by peer
> 2016-12-21 23:51:17 ERROR    tcprelay.py:1058 when connect to zhaoj.in:80 from ::ffff:223.104.177.16:32165 via port 13800
> 2016-12-21 23:51:18 ERROR    tcprelay.py:899 The host: md5 is mismatch,so The connection has been rejected, when connect from ::ffff:223.104.177.16:32166 via > port 13800
> 2016-12-21 23:51:18 WARNING  tcprelay.py:474 Protocol ERROR, TCP ogn data 474554202f256664253131……（中间略去TCP数据）……e9f782826a21f582319d4b93ac4931c047 >from ::ffff:223.104.177.16:32166 via port 13800

ssr端的userapiconfig:

> # Config
> NODE_ID = 3
> #hour,set 0 to disable
> SPEEDTEST = 6
> CLOUDSAFE = 1
> ANTISSATTACK = 0
> AUTOEXEC = 0
> MULTI_THREAD = 0
> 
> MU_SUFFIX = 'baidu.com'
> MU_REGEX = '%5m%id.%suffix'
> 
> SERVER_PUB_ADDR = '127.0.0.1' # mujson_mgr need this to generate ssr link
> API_INTERFACE = 'glzjinmod' #mudbjson, sspanelv2, sspanelv3, sspanelv3ssr, muapiv2(not support)
> 
> #mudb
> MUDB_FILE = 'mudb.json'
> 
> # Mysql
> MYSQL_HOST = 'XX.XX.XX.XX'
> MYSQL_PORT = 3306
> MYSQL_USER = 'XXXX'
> MYSQL_PASS = '*************'
> MYSQL_DB = 'XXXXX'
> MYSQL_UPDATE_TIME = 60
> 
> MYSQL_SSL_ENABLE = 0
> MYSQL_SSL_CA = ''
> MYSQL_SSL_CERT = ''
> MYSQL_SSL_KEY = ''
> 
> # API
> API_HOST = '127.0.0.1'
> API_PORT = 80
> API_PATH = '/mu/v2/'
> API_TOKEN = 'abcdef'
> API_UPDATE_TIME = 60
> 
> # Manager (ignore this)
> MANAGE_PASS = 'ss233333333'
> #if you want manage in other server you should set this value to global ip
> MANAGE_BIND_IP = '127.0.0.1'
> #make sure this port is idle
> MANAGE_PORT = 23333
> 

user-condig.json:

> {
>     "server": "0.0.0.0",
>     "server_ipv6": "::",
>     "server_port": 8388,
>     "local_address": "127.0.0.1",
>     "local_port": 1080,
>     "password": "m",
>     "timeout": 120,
>     "udp_timeout": 60,
>     "method": "aes-256-cfb",
>     "protocol": "auth_sha1_v4_compatible",
>     "protocol_param": "",
>     "obfs": "tls1.2_ticket_auth_compatible",
>     "obfs_param": "",
>     "dns_ipv6": false,
>     "connect_verbose_info": 0,
>     "connect_hex_data": 0,
>     "redirect": "*-zhaoj.in:80",
>     "fast_open": false
> }

SS-Panel端.config.php的相关设置（前面与后端无关的地方已经略去）：

> #telegram bot,是否启用
> $System_Config['enable_telegram']='false';
> 
> #telegram bot,bot 的 token ，跟 father bot 申请
> $System_Config['telegram_token']='';
> 
> #telegram bot,群组会话 ID,把机器人拉进群里之后跟他 /ping 一下即可得到。
> $System_Config['telegram_chatid']='';
> 
> #多用户混淆参数后缀
> $System_Config['MU_SUFFIX']='baidu.com';
> 
> #多用户混淆参数表达式，%5m代表取用户特征 md5 的前五位，%id 代表用户id,%suffix 代表上面这个后缀。
> $System_Config['MU_REGEX']='%5m%id.%suffix';

P.S.:redirect参数我用不到，但是置空的话一样也会报错：

> 2016-12-21 23:58:07 ERROR    tcprelay.py:925 exception from ::ffff:223.104.177.16:33350
> 2016-12-21 23:58:08 ERROR    tcprelay.py:899 The host: md5 is mismatch,so The connection has been rejected, when connect from ::ffff:223.104.177.16:33351 via port 13800
> 2016-12-21 23:58:08 WARNING  tcprelay.py:474 Protocol ERROR, TCP ogn data 474554202f2537372537632564……………………b6e12cb746342a341907cbaf3b2 from ::ffff:223.104.177.16:33351 via port 13800
> 2016-12-21 23:58:08 ERROR    shell.py:50 can not parse header
>

**Comment by hawkhu** [comment]
话说这在线编辑器……

**Comment by hawkhu** [comment]
自己改了一下代码，把tcprelay.py中关于用户ID的判断条件：
`            if self._server._config["is_multi_user"] == 1 and self._current_user_id ==0`
改成了
`            if self._server._config["is_multi_user"] == 1 and self._current_user_id <>0`
绕过了异常代码段，舍弃掉了tcprelay的功能。
没有通读代码，不知道怎么修改。。

**Comment by glzjin** [comment]
@hawkhu 你自己没有设置好正确的连接参数

**Comment by hawkhu** [comment]
@glzjin 那请问是哪些参数没有设置对呢?

**Comment by conglu930** [comment]
@hawkhu 请问问题解决了吗？我跟你有同样的问题，方便告知下如何解决的吗？谢谢

**Comment by 693098385** [comment]
登录密码是"单端口多用户承载端口""用户"的密码
