### ISSUE TITLE
100人在线节点在线ip上报只有10几个

### ISSUE THREAD

**Issue by bigbigname** [esdeathlove/shadowsocks#32]
请问为什么同一个节点上报的ip，只有那么几个呢，这样的话，就无法限制同一用户的登陆ip数量了。
会是什么原因呢

**Comment by glzjin** [comment]
@bigbigname 你怎么知道一百人在线的。。。

**Comment by bigbigname** [comment]
因为前端面板上有在线人数统计呢  赵大大的前端面板特好用

**Comment by bigbigname** [comment]
这边4个节点，此时我这边在线200多人，后台的在线ip人数就20多个，好凄惨

**Comment by glzjin** [comment]
@bigbigname 你发下截图看看？

**Comment by glzjin** [comment]
@bigbigname 还有别去数在线IP表

**Comment by bigbigname** [comment]
![111](https://cloud.githubusercontent.com/assets/24818656/21544266/94bf8f30-ce08-11e6-96e8-09398c716e43.jpg)

![222](https://cloud.githubusercontent.com/assets/24818656/21544260/88cf70dc-ce08-11e6-801c-126886881181.jpg)

**Comment by bigbigname** [comment]
啊，前台统计那么多人，后台的节点在线ip人数，就2页...

**Comment by glzjin** [comment]
@bigbigname 别数了 前端是准确的在线人数 后端的IP表是请求的时候往前60s之内的IP数 可能没有被select进去

**Comment by bigbigname** [comment]
嗯嗯，感谢赵老师这么迅捷的回复，有问题我还来提问。
我的站点，主页我换了个单页面主页，STAFF链接和页面没有改动，并且加在了主页上。
用户中心改动了一下，特别是充值系统。
好多用户傻傻的充值充值码，就以为买到了流量，不知道要去商店购买，这一步骤确实让小白犯难了~~

**Comment by glzjin** [comment]
@bigbigname 那你就告诉他们他们应该如何做吧

**Comment by bigbigname** [comment]
我给它在数据库mysql里加了个循环执行命令，10秒钟执行一次，凡是充值了10元的，自动加上10G流量...类似这样
