### ISSUE TITLE
这种情况如何处理：后加入新的节点后，以前的用户获取不到

### ISSUE THREAD

**Issue by trumphi** [esdeathlove/shadowsocks#36]
比如现在已有两个节点A和B，并且注册了三个用户，之后新增了一个节点C，然后打开其中一个用户的面板，发现不显示这个新增的C，我不知道是否还有什么设置一下才能让C显示？

**Comment by esdeathlove** [comment]
检查节点等级和群组与用户的是否匹配。2017年1月21日 下午11:00，trumphi <notifications@github.com>写道：比如现在已有两个节点A和B，并且注册了三个用户，之后新增了一个节点C，然后打开其中一个用户的面板，发现不显示这个新增的C，我不知道是否还有什么设置一下才能让C显示？

**Comment by trumphi** [comment]
管理员的用户中心里都不显示，别的更不显示

**Comment by esdeathlove** [comment]
@trumphi 等级和群组是绝对的，不因为你是管理员而失效。

**Comment by trumphi** [comment]
目前所有用户都不显示这个新增的节点

**Comment by esdeathlove** [comment]
@trumphi 我请你检查一下节点的等级和群组好吗？

**Comment by trumphi** [comment]
我查了一下，新增的节点和群组等级各为0

**Comment by esdeathlove** [comment]
@trumphi 截图下你这个节点的信息和你自己的用户信息还有用户列表。

**Comment by trumphi** [comment]
我是按默认设置来的，几乎全是默认设置

**Comment by esdeathlove** [comment]
@trumphi 我请你截图好吗？

**Comment by trumphi** [comment]
<img src="https://raw.githubusercontent.com/trumphi/tupian/master/1.png"/>
<img src="https://raw.githubusercontent.com/trumphi/tupian/master/2.png"/>

**Comment by esdeathlove** [comment]
@trumphi 上面呢？

**Comment by trumphi** [comment]
没明白，上面指的是哪里，这个页的上面还是啥？

**Comment by esdeathlove** [comment]
@trumphi 对的。

**Comment by trumphi** [comment]
难道我设置有问题？
