### ISSUE TITLE
后端无法自动打开端口

### ISSUE THREAD

**Issue by silentstage** [esdeathlove/shadowsocks#39]
我A，B，C三个节点，A节点装了SSpanel+后端，一切正常，新用户注册也能自动打开端口
B，C节点都只装了后端，看log文件，在A前台修改用户端口后，B，C后端也自动切换了端口，但是客户端无法连接，手动打开相应端口后就连接正常了。B，C节点都有LNMP环境，Centos6*64。谢谢

**Comment by esdeathlove** [comment]
这个自己想办法解决。
