### ISSUE TITLE
更新到02/04版本后,魔改版后台用户IP地址显示乱码

### ISSUE THREAD

**Issue by sophauer** [esdeathlove/shadowsocks#41]
按提示在 userapiconfig.py 里添加一个设置项。

#Safety

IP_MD5_SALT = 'randomforsafety'

到魔改版后台页面发现用户来源IP地址全变成乱码了

**Comment by esdeathlove** [comment]
更新前端。

**Comment by sophauer** [comment]
谢谢回覆,不过,git pull出错,显示
vendor/aws/aws-sdk-php/src/data/cognito-idp/2016-04-18/api-2.json.php
        ven
Aborting
