### ISSUE TITLE
开启多线程后部分服务器出现断流情况

### ISSUE THREAD

**Issue by JohnFreeman9** [esdeathlove/shadowsocks#42]
情况描述如下：
1、魔改服务端2017/02/10+libsodium-1.0.11依赖，启用多线程、两个安全选项
2、节点参考SS总支提到的参数进行了优化（魔改后端安装说明也有提到）
3、节点配置为：樱花虚拟单双核两种配置、微软云单核配置

在上述情况下，进行VULTR的1G文件下载基准测试，出现随机断流情况，服务端提示104错误connection reset by peers，客户端同时提示ClientPostDecrypt data error。

禁用多线程的情况下无任何问题，但禁用多线程时限速功能无效。
有趣的是，某些美国L5630分配2CPU资源的机子却完全没有问题，因此作了如下尝试：
1、重新部署了整套魔改系统前后端，更换前端所在的服务器地理位置，修正前端mysql相关参数
2、购买含有更多CPU资源的VPS
3、禁用防火墙
4、不进行节点参数优化
*但上述尝试皆无法解决问题。

因此请问一下上述情况可有解决方案。

**Comment by esdeathlove** [comment]
开了锐速等加速软件否？

**Comment by JohnFreeman9** [comment]
在使用91云锐速、某502论坛的LotServer、完全新装不采用任何加速软件的情况下均有出现

**Comment by jimorsm** [comment]
你好，请问下你的lotserver在哪儿下的？

2017年2月11日 上午11:14，"JohnFreeman9" <notifications@github.com>写道：
