### ISSUE TITLE
有一个js崩了

### ISSUE THREAD

**Issue by Luobogao** [esdeathlove/shadowsocks#46]
刚才（2017年2月21日）收到tg说有更新，
然后git pull了一下
然后后台所有交易功能都提示如下：
![dmg 9 ir zk b 0ul 2th](https://cloud.githubusercontent.com/assets/13681639/23131886/17086706-f7cf-11e6-95d7-65377b44f9d1.png)

**Comment by esdeathlove** [comment]
https://github.com/esdeathlove/ss-panel-v3-mod/issues

请仔细阅读更新说明。
